---
- name: First playbook
  hosts: node
  tasks:
      - name: ping test
        ping:
...
---
- hosts: node
  tasks:
   - name: install http
     yum: name=httpd state=absent
---
- name: install multiple pacakage
  hosts: node
  tasks:
    - name: install package
      yum: name={{item}} state=latest
      with_items:
      - make
      - gcc
      - httpd
      - wget
...
